/**/gait_manager:
  ros__parameters:
    # Interpolation parameters
    angular_speed_deg_s: 20.0
    joint_tol_deg: 3.0

    # Hexapod gait
    # 0 - all legs in stance
    # 1 - B lifts up
    # 2 - B moves above position (+25 deg), A pushes (-25 deg)
    # 3 - B places down
    # 4 - A lifts up
    # 5 - A moves above position, B pushes
    # 6 - A places down
    gait:
      back_left_leg:
        0: [-15.0, -10.0, 100.0]
        1: [-15.0, -10.0, 100.0]
        2: [-40.0, -10.0, 100.0]
        3: [-40.0, -10.0, 100.0]
        4: [-40.0, -45.0, 90.0]
        5: [-15.0, -45.0, 90.0]

      back_right_leg:
        0: [-15.0, 10.0, -100.0]
        1: [-15.0, 45.0, -90.0]
        2: [10.0, 45.0, -90.0]
        3: [10.0, 10.0, -100.0]
        4: [10.0, 10.0, -100.0]
        5: [-15.0, 10.0, -100.0]

      middle_left_leg:
        0: [25.0, -10.0, 100.0]
        1: [25.0, -45.0, 90.0]
        2: [50.0, -45.0, 90.0]
        3: [50.0, -10.0, 100.0]
        4: [50.0, -10.0, 100.0]
        5: [25.0, -10.0, 100.0]

      middle_right_leg:
        0: [25.0, 10.0, -100.0]
        1: [25.0, 10.0, -100.0]
        2: [0.0, 10.0, -100.0]
        3: [0.0, 10.0, -100.0]
        4: [0.0, 45.0, -90.0]
        5: [25.0, 45.0, -90.0]

      front_left_leg:
        0: [25.0, -10.0, 100.0]
        1: [25.0, -10.0, 100.0]
        2: [0.0, -10.0, 100.0]
        3: [0.0, -10.0, 100.0]
        4: [0.0, -45.0, 90.0]
        5: [25.0, -45.0, 90.0]

      front_right_leg:
        0: [25.0, 10.0, -100.0]
        1: [25.0, 45.0, -90.0]
        2: [50.0, 45.0, -90.0]
        3: [50.0, 10.0, -100.0]
        4: [50.0, 10.0, -100.0]
        5: [25.0, 10.0, -100.0]
