/**/gait_manager:
  ros__parameters:
    # Interpolation parameters
    angular_speed_deg_s: 30.0
    joint_tol_deg: 2.0

    # Hexapod gait
    gait:
      back_left_leg:
        0: [-15., -45., 90.]
        1: [-15., -10., 100.]
        2: [-15., -10., 100.]
        3: [-15., -10., 100.]

      back_right_leg:
        0: [-15., 10., -100.]
        1: [-40., 10., -100.]
        2: [-15., 45., -90.]
        3: [-15., 10., -100.]

      middle_left_leg:
        0: [25., -10., 100.]
        1: [0., -10., 100.]
        2: [25., -45., 90.]
        3: [25., -10., 100.]

      middle_right_leg:
        0: [25., 45., -90.]
        1: [25., 10., -100.]
        2: [25., 10., -100.]
        3: [25., 10., -100.]

      front_left_leg:
        0: [65., -45., 90.]
        1: [65., -10., 100.]
        2: [65., -10., 100.]
        3: [65., -10., 100.]

      front_right_leg:
        0: [65., 10., -100.]
        1: [40., 10., -100.]
        2: [65., 45., -90.]
        3: [65., 10., -100.]
