/**/gait_manager:
  ros__parameters:
    # Interpolation parameters
    angular_speed_deg_s: 30.0
    joint_tol_deg: 2.0

    # Turtle gait
    gait:
      back_left_leg:
        0: [0., -35., 100.]
        1: [40., -35., 100.]
        2: [40., -10., 100.]
        3: [0., 0., 100.]

      back_right_leg:
        0: [0., 35., -100.]
        1: [40., 35., -100.]
        2: [40., 10., -100.]
        3: [0., 0., -100.]

      front_left_leg:
        0: [0., -35., 100.]
        1: [40., -35., 100.]
        2: [40., -10., 100.]
        3: [0., 0., 100.]

      front_right_leg:
        0: [0., 35., -100.]
        1: [40., 35., -100.]
        2: [40., 10., -100.]
        3: [0., 0., -100.]
